#pragma once
#ifndef CONSTANTS_H
#define CONSTANTS_H
#define WIN_WIDTH 540
#define WIN_HEIGHT 600

#define CHAR_WIDTH 10
#define CHAR_HEIGHT 30 

#define BLOCK_WIDTH 22
#define BLOCK_GAP 3

#define SCORE_LENGTH 18

#define TETRIS_SIZE_W 10
#define TETRIS_SIZE_H 20
#define TETRIS_WIDTH (TETRIS_SIZE_W * (BLOCK_WIDTH + BLOCK_GAP))
#define TETRIS_HEIGHT (TETRIS_SIZE_H * (BLOCK_WIDTH + BLOCK_GAP))

#endif
